# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StudyAtMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StudyAtMobile
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.4'
  pod 'Firebase/Crash', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'

  target 'StudyAtMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'StudyAtMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StudyAtMobile-tvOS

  target 'StudyAtMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
